version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: tomuser
      POSTGRES_PASSWORD: tompass
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - my-postgres-volume:/var/lib/postgresql/data

  backend:
    build:
      context: ./hft-23-winter-middleware-backend
      dockerfile: Dockerfile-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/todoapp
      SPRING_DATASOURCE_USERNAME: tomuser
      SPRING_DATASOURCE_PASSWORD: tompass

  frontend:
    build:
      context: ./hft-23-winter-middleware-frontend
      dockerfile: Dockerfile-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  my-postgres-volume: