# Use an official Maven/Java image as a base image
FROM maven:3-eclipse-temurin-21-alpine AS backend-build

WORKDIR /app
COPY . /app
WORKDIR /app
RUN mvn clean install

# Final image
FROM openjdk:23-jdk-slim
WORKDIR /app
COPY --from=backend-build /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]