# Use an official Node.js image as a base image
FROM node:14-alpine AS frontend-build

WORKDIR /app
COPY . /app
WORKDIR /app
RUN npm install
RUN npm run build

# Final image
FROM nginx:alpine
COPY --from=frontend-build /app/build /usr/share/nginx/html